<a href="https://colab.research.google.com/github/zombe962/2021_math_python/blob/main/%ED%86%B5%EA%B3%8410_fifa%ED%8C%80_index_%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving FIFA 2018 Statistics.csv to FIFA 2018 Statistics.csv

In [ ]:
pd.read_csv('FIFA 2018 Statistics.csv')

           Date          Team  ... Own goals  Own goal Time
0    14-06-2018        Russia  ...       NaN            NaN
1    14-06-2018  Saudi Arabia  ...       NaN            NaN
2    15-06-2018         Egypt  ...       NaN            NaN
3    15-06-2018       Uruguay  ...       NaN            NaN
4    15-06-2018       Morocco  ...       1.0           90.0
..          ...           ...  ...       ...            ...
123  11-07-2018       England  ...       NaN            NaN
124  14-07-2018       Belgium  ...       NaN            NaN
125  14-07-2018       England  ...       NaN            NaN
126  15-07-2018        France  ...       1.0           18.0
127  15-07-2018       Croatia  ...       NaN            NaN

[128 rows x 27 columns]

In [ ]:
fifa = pd.read_csv('FIFA 2018 Statistics.csv')

print(fifa.index)
print(fifa.columns)
print(len(fifa.columns))

RangeIndex(start=0, stop=128, step=1)
Index(['Date', 'Team', 'Opponent', 'Goal Scored', 'Ball Possession %',
       'Attempts', 'On-Target', 'Off-Target', 'Blocked', 'Corners', 'Offsides',
       'Free Kicks', 'Saves', 'Pass Accuracy %', 'Passes',
       'Distance Covered (Kms)', 'Fouls Committed', 'Yellow Card',
       'Yellow & Red', 'Red', 'Man of the Match', '1st Goal', 'Round', 'PSO',
       'Goals in PSO', 'Own goals', 'Own goal Time'],
      dtype='object')
27

In [ ]:
pd.set_option('display.max_rows', 200)  # 최대 줄수 설정
fifa[:]

           Date            Team  ... Own goals  Own goal Time
0    14-06-2018          Russia  ...       NaN            NaN
1    14-06-2018    Saudi Arabia  ...       NaN            NaN
2    15-06-2018           Egypt  ...       NaN            NaN
3    15-06-2018         Uruguay  ...       NaN            NaN
4    15-06-2018         Morocco  ...       1.0           90.0
5    15-06-2018            Iran  ...       NaN            NaN
6    15-06-2018        Portugal  ...       NaN            NaN
7    15-06-2018           Spain  ...       NaN            NaN
8    16-06-2018          France  ...       NaN            NaN
9    16-06-2018       Australia  ...       1.0           81.0
10   16-06-2018       Argentina  ...       NaN            NaN
11   16-06-2018         Iceland  ...       NaN            NaN
12   16-06-2018            Peru  ...       NaN            NaN
13   16-06-2018         Denmark  ...       NaN            NaN
14   17-06-2018         Croatia  ...       NaN            NaN
15   17-06-2018         Nigeria  ...       1.0           32.0
16   17-06-2018      Costa Rica  ...       NaN            NaN
17   17-06-2018          Serbia  ...       NaN            NaN
18   17-06-2018         Germany  ...       NaN            NaN
19   17-06-2018          Mexico  ...       NaN            NaN
20   17-06-2018          Brazil  ...       NaN            NaN
21   17-06-2018     Switzerland  ...       NaN            NaN
22   18-06-2018          Sweden  ...       NaN            NaN
23   18-06-2018  Korea Republic  ...       NaN            NaN
24   18-06-2018         Belgium  ...       NaN            NaN
25   18-06-2018          Panama  ...       NaN            NaN
26   18-06-2018         Tunisia  ...       NaN            NaN
27   18-06-2018         England  ...       NaN            NaN
28   19-06-2018        Colombia  ...       NaN            NaN
29   19-06-2018           Japan  ...       NaN            NaN
30   19-06-2018          Poland  ...       1.0           37.0
31   19-06-2018         Senegal  ...       NaN            NaN
32   19-06-2018          Russia  ...       NaN            NaN
33   19-06-2018           Egypt  ...       1.0           47.0
34   20-06-2018        Portugal  ...       NaN            NaN
35   20-06-2018         Morocco  ...       NaN            NaN
36   20-06-2018         Uruguay  ...       NaN            NaN
37   20-06-2018    Saudi Arabia  ...       NaN            NaN
38   20-06-2018            Iran  ...       NaN            NaN
39   20-06-2018           Spain  ...       NaN            NaN
40   21-06-2018         Denmark  ...       NaN            NaN
41   21-06-2018       Australia  ...       NaN            NaN
42   21-06-2018          France  ...       NaN            NaN
43   21-06-2018            Peru  ...       NaN            NaN
44   21-06-2018       Argentina  ...       NaN            NaN
45   21-06-2018         Croatia  ...       NaN            NaN
46   22-06-2018          Brazil  ...       NaN            NaN
47   22-06-2018      Costa Rica  ...       NaN            NaN
48   22-06-2018         Nigeria  ...       NaN            NaN
49   22-06-2018         Iceland  ...       NaN            NaN
50   22-06-2018          Serbia  ...       NaN            NaN
51   22-06-2018     Switzerland  ...       NaN            NaN
52   23-06-2018         Belgium  ...       NaN            NaN
53   23-06-2018         Tunisia  ...       NaN            NaN
54   23-06-2018  Korea Republic  ...       NaN            NaN
55   23-06-2018          Mexico  ...       NaN            NaN
56   23-06-2018         Germany  ...       NaN            NaN
57   23-06-2018          Sweden  ...       NaN            NaN
58   24-06-2018         England  ...       NaN            NaN
59   24-06-2018          Panama  ...       NaN            NaN
60   24-06-2018           Japan  ...       NaN            NaN
61   24-06-2018         Senegal  ...       NaN            NaN
62   24-06-2018          Poland  ...       NaN            NaN
63   24-06-2018        Colombia  ...       NaN            NaN
64   25-06-2018         Uruguay  ...       NaN            NaN
65   25-06-2018          Russia  ...       1.0           23.0
66   25-06-2018    Saudi Arabia  ...       NaN            NaN
67   25-06-2018           Egypt  ...       NaN            NaN
68   25-06-2018           Spain  ...       NaN            NaN
69   25-06-2018         Morocco  ...       NaN            NaN
70   25-06-2018            Iran  ...       NaN            NaN
71   25-06-2018        Portugal  ...       NaN            NaN
72   26-06-2018         Denmark  ...       NaN            NaN
73   26-06-2018          France  ...       NaN            NaN
74   26-06-2018       Australia  ...       NaN            NaN
75   26-06-2018            Peru  ...       NaN            NaN
76   26-06-2018         Nigeria  ...       NaN            NaN
77   26-06-2018       Argentina  ...       NaN            NaN
78   26-06-2018         Iceland  ...       NaN            NaN
79   26-06-2018         Croatia  ...       NaN            NaN
80   27-06-2018  Korea Republic  ...       NaN            NaN
81   27-06-2018         Germany  ...       NaN            NaN
82   27-06-2018          Mexico  ...       1.0           74.0
83   27-06-2018          Sweden  ...       NaN            NaN
84   27-06-2018          Serbia  ...       NaN            NaN
85   27-06-2018          Brazil  ...       NaN            NaN
86   27-06-2018     Switzerland  ...       1.0           90.0
87   27-06-2018      Costa Rica  ...       NaN            NaN
88   28-06-2018           Japan  ...       NaN            NaN
89   28-06-2018          Poland  ...       NaN            NaN
90   28-06-2018         Senegal  ...       NaN            NaN
91   28-06-2018        Colombia  ...       NaN            NaN
92   28-06-2018          Panama  ...       NaN            NaN
93   28-06-2018         Tunisia  ...       1.0           33.0
94   28-06-2018         England  ...       NaN            NaN
95   28-06-2018         Belgium  ...       NaN            NaN
96   30-06-2018          France  ...       NaN            NaN
97   30-06-2018       Argentina  ...       NaN            NaN
98   30-06-2018         Uruguay  ...       NaN            NaN
99   30-06-2018        Portugal  ...       NaN            NaN
100  01-07-2018           Spain  ...       NaN            NaN
101  01-07-2018          Russia  ...       1.0           12.0
102  01-07-2018         Croatia  ...       NaN            NaN
103  01-07-2018         Denmark  ...       NaN            NaN
104  02-07-2018          Brazil  ...       NaN            NaN
105  02-07-2018          Mexico  ...       NaN            NaN
106  02-07-2018         Belgium  ...       NaN            NaN
107  02-07-2018           Japan  ...       NaN            NaN
108  03-07-2018          Sweden  ...       NaN            NaN
109  03-07-2018     Switzerland  ...       NaN            NaN
110  03-07-2018        Colombia  ...       NaN            NaN
111  03-07-2018         England  ...       NaN            NaN
112  06-07-2018         Uruguay  ...       NaN            NaN
113  06-07-2018          France  ...       NaN            NaN
114  06-07-2018          Brazil  ...       1.0           13.0
115  06-07-2018         Belgium  ...       NaN            NaN
116  07-07-2018          Sweden  ...       NaN            NaN
117  07-07-2018         England  ...       NaN            NaN
118  07-07-2018          Russia  ...       NaN            NaN
119  07-07-2018         Croatia  ...       NaN            NaN
120  10-07-2018          France  ...       NaN            NaN
121  10-07-2018         Belgium  ...       NaN            NaN
122  11-07-2018         Croatia  ...       NaN            NaN
123  11-07-2018         England  ...       NaN            NaN
124  14-07-2018         Belgium  ...       NaN            NaN
125  14-07-2018         England  ...       NaN            NaN
126  15-07-2018          France  ...       1.0           18.0
127  15-07-2018         Croatia  ...       NaN            NaN

[128 rows x 27 columns]

In [ ]:
fifa[1:4]

         Date          Team Opponent  ...  Goals in PSO  Own goals  Own goal Time
1  14-06-2018  Saudi Arabia   Russia  ...             0        NaN            NaN
2  15-06-2018         Egypt  Uruguay  ...             0        NaN            NaN
3  15-06-2018       Uruguay    Egypt  ...             0        NaN            NaN

[3 rows x 27 columns]

In [ ]:
fifa.head(3)    # 위부터 세번째

         Date          Team  ... Own goals  Own goal Time
0  14-06-2018        Russia  ...       NaN            NaN
1  14-06-2018  Saudi Arabia  ...       NaN            NaN
2  15-06-2018         Egypt  ...       NaN            NaN

[3 rows x 27 columns]

In [ ]:
fifa.tail(3)    # 밑에서 세번째

           Date     Team Opponent  ...  Goals in PSO  Own goals  Own goal Time
125  14-07-2018  England  Belgium  ...             0        NaN            NaN
126  15-07-2018   France  Croatia  ...             0        1.0           18.0
127  15-07-2018  Croatia   France  ...             0        NaN            NaN

[3 rows x 27 columns]

In [ ]:
fifateam = fifa.set_index('Team')

In [ ]:
kor = fifateam.loc['Korea Republic']
kor

                      Date Opponent  ...  Own goals  Own goal Time
Team                                 ...
Korea Republic  18-06-2018   Sweden  ...        NaN            NaN
Korea Republic  23-06-2018   Mexico  ...        NaN            NaN
Korea Republic  27-06-2018  Germany  ...        NaN            NaN

[3 rows x 26 columns]

In [ ]:
kor.mean()

Goal Scored                 1.000000
Ball Possession %          39.666667
Attempts                   11.000000
On-Target                   3.666667
Off-Target                  3.000000
Blocked                     4.333333
Corners                     5.000000
Offsides                    0.000000
Free Kicks                 12.000000
Saves                       4.333333
Pass Accuracy %            78.333333
Passes                    311.333333
Distance Covered (Kms)    106.666667
Fouls Committed            21.000000
Yellow Card                 3.333333
Yellow & Red                0.000000
Red                         0.000000
1st Goal                   90.000000
Goals in PSO                0.000000
Own goals                        NaN
Own goal Time                    NaN
dtype: float64

In [ ]:
kor.var()

Goal Scored                  1.000000
Ball Possession %           82.333333
Attempts                    36.000000
On-Target                   10.333333
Off-Target                   3.000000
Blocked                     17.333333
Corners                      4.000000
Offsides                     0.000000
Free Kicks                  61.000000
Saves                        5.333333
Pass Accuracy %             16.333333
Passes                    4150.333333
Distance Covered (Kms)     100.333333
Fouls Committed             19.000000
Yellow Card                  1.333333
Yellow & Red                 0.000000
Red                          0.000000
1st Goal                     0.000000
Goals in PSO                 0.000000
Own goals                         NaN
Own goal Time                     NaN
dtype: float64

In [ ]:
kor.std()

Goal Scored                1.000000
Ball Possession %          9.073772
Attempts                   6.000000
On-Target                  3.214550
Off-Target                 1.732051
Blocked                    4.163332
Corners                    2.000000
Offsides                   0.000000
Free Kicks                 7.810250
Saves                      2.309401
Pass Accuracy %            4.041452
Passes                    64.423081
Distance Covered (Kms)    10.016653
Fouls Committed            4.358899
Yellow Card                1.154701
Yellow & Red               0.000000
Red                        0.000000
1st Goal                   0.000000
Goals in PSO               0.000000
Own goals                       NaN
Own goal Time                   NaN
dtype: float64

In [ ]:
len(set(fifateam.index))    # 전체 팀의 갯수

32

In [ ]:
a = []     # 전체 팀의 갯수
for i in fifateam.index:
    if i not in a:
        a.append(i)

print(len(a))

32